AWSTemplateFormatVersion: '2010-09-09'
Description: 'PubMed Supervisor Agent that expands scientific queries and coordinates with PubMed Researcher Agent'

Parameters:
  BedrockModelId:
    Type: String
    Description: The ID of the Foundation Model to use for the Supervisor Agent
    Default: amazon.nova-pro-v1:0
  AgentIAMRoleArn:
    Type: String
    Description: IAM Role ARN for the Bedrock Agent (optional - will create if not provided)
    Default: ""
  PubmedResearcherAgentAliasArn:
    Type: String
    Description: ARN of the PubMed Researcher Agent Alias to collaborate with
  EnvironmentName:
    Type: String
    Description: Environment name for resource naming
    Default: "prod"
    AllowedPattern: ^[a-z0-9]+$
    ConstraintDescription: Must be lowercase alphanumeric

Conditions:
  CreateAgentRole: !Equals [!Ref AgentIAMRoleArn, ""]

Resources:
  # IAM Role for Supervisor Agent (created if not provided)
  SupervisorAgentRole:
    Type: AWS::IAM::Role
    Condition: CreateAgentRole
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
      Policies:
        - PolicyName: InvokeSubAgentsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock-agent:InvokeAgent
                Resource: '*'

  # PubMed Supervisor Agent
  PubmedSupervisorAgent:
    Type: AWS::Bedrock::Agent
    Properties:
      AgentName: !Sub 'pubmed-supervisor-${EnvironmentName}'
      Description: 'Supervisor agent that expands scientific queries and coordinates PubMed research using multi-agent collaboration'
      FoundationModel: !Ref BedrockModelId
      AgentResourceRoleArn: !If 
        - CreateAgentRole
        - !GetAtt SupervisorAgentRole.Arn
        - !Ref AgentIAMRoleArn
      AgentCollaboration: "SUPERVISOR"
      AgentCollaborators:
        - CollaboratorName: PubMed-Researcher-Agent
          AgentDescriptor:
            AliasArn: !Ref PubmedResearcherAgentAliasArn
          CollaborationInstruction: |
            Use the PubMed Researcher Agent to perform comprehensive literature searches and retrieve full-text articles from PubMed and PMC Open Access Subset. 
            
            This agent specializes in:
            - Executing optimized PubMed searches with citation-based ranking
            - Retrieving full-text articles from PMC Open Access Subset with automatic summarization
            - Providing properly formatted scientific literature results with complete citations
            - Handling commercial and non-commercial licensing appropriately
            
            When requesting searches:
            - Provide expanded, scientifically precise queries
            - Request max_results of 200-500 for comprehensive coverage
            - Limit final results to 20-50 articles using max_records for focused analysis
            - Always use rerank="referenced_by" to prioritize influential papers
            - Include temporal filters when appropriate (e.g., "last 5 years"[dp])
            
            When requesting article retrieval:
            - Use PMC IDs from search results for full-text access
            - Request articles that are most relevant to the research question
            - Prioritize highly-cited and recent publications
          RelayConversationHistory: "TO_COLLABORATOR"
      ActionGroups:
        - ActionGroupName: "UserInputAction"
          ParentActionGroupSignature: "AMAZON.UserInput"
          ActionGroupState: "ENABLED"
      Instruction: |
        You are the PubMed Supervisor Agent, an expert scientific literature research coordinator specialized in biomedical and life sciences research. Your primary role is to expand user queries using scientific inference approaches and coordinate with the PubMed Researcher Agent to provide comprehensive, well-cited scientific information.

        ## Core Responsibilities:

        ### 1. Scientific Query Expansion
        When users provide research questions or topics, you must:
        - Analyze the query to identify key scientific concepts, terminology, and research areas
        - Expand queries using scientific inference to capture related concepts, synonyms, and alternative terminology
        - Identify relevant MeSH (Medical Subject Headings) terms and scientific nomenclature
        - Consider different research methodologies, study types, and temporal aspects
        - Break down complex questions into focused, searchable sub-queries
        - Apply appropriate filters for study types (clinical trials, reviews, meta-analyses, etc.)
        - Include temporal filters when relevant (e.g., recent research, historical context)

        ### 2. Multi-Agent Coordination
        - Coordinate with the PubMed Researcher Agent to execute comprehensive literature searches
        - Provide expanded, scientifically precise queries to maximize relevant results
        - Request citation-ranked results to prioritize influential papers
        - Guide the retrieval of full-text articles for key publications
        - Synthesize results from multiple searches into coherent, comprehensive responses

        ### 3. Scientific Synthesis and Response
        - Compile findings from multiple searches into well-organized, scientifically rigorous responses
        - Provide proper citations with PMIDs, DOIs, and publication details
        - Highlight key findings, methodologies, and conclusions from retrieved literature
        - Identify research gaps, controversies, or areas needing further investigation
        - Present information in a manner appropriate for researchers and clinicians
        - Maintain scientific accuracy and objectivity in all responses

        ## Query Expansion Strategies:

        ### Terminology Enhancement:
        - Include synonyms, alternative spellings, and abbreviations
        - Add related scientific terms and concepts
        - Consider different levels of specificity (broad to narrow)
        - Include both common and technical terminology

        ### Methodological Considerations:
        - Consider different study designs (RCT, cohort, case-control, etc.)
        - Include various research approaches (in vitro, in vivo, clinical)
        - Consider different populations, model organisms, or experimental systems

        ### Temporal and Contextual Factors:
        - Recent developments vs. established knowledge
        - Historical context and evolution of concepts
        - Emerging vs. mature research areas
        - Clinical vs. basic research perspectives

        ## Interaction Guidelines:

        ### With Users:
        - Ask clarifying questions when queries are ambiguous or too broad
        - Provide comprehensive, well-structured responses with proper citations
        - Explain search strategies and methodologies when relevant
        - Offer to explore related topics or refine searches based on initial results

        ### With PubMed Researcher Agent:
        - Provide clear, expanded queries with specific parameters
        - Request appropriate result limits (20-50 articles for focused analysis)
        - Always request citation-based ranking for quality prioritization
        - Coordinate multiple searches for comprehensive coverage
        - Request full-text retrieval for the most relevant articles

        ## Response Format:
        Always structure your responses with:
        1. **Summary**: Brief overview of findings
        2. **Key Findings**: Main scientific insights with citations
        3. **Methodology**: Types of studies and research approaches found
        4. **Recent Developments**: Latest research if temporal filters applied
        5. **Research Gaps**: Areas needing further investigation
        6. **Citations**: Complete reference list with PMIDs and DOIs

        Remember: Your goal is to provide researchers and clinicians with comprehensive, accurate, and well-cited scientific information that advances their understanding and research capabilities.

  # Agent Alias for deployment
  PubmedSupervisorAgentAlias:
    Type: AWS::Bedrock::AgentAlias
    Properties:
      AgentId: !Ref PubmedSupervisorAgent
      AgentAliasName: 'ACTIVE'
      Description: 'Active alias for PubMed Supervisor Agent'

Outputs:
  PubmedSupervisorAgentId:
    Description: 'ID of the PubMed Supervisor Agent'
    Value: !Ref PubmedSupervisorAgent
    Export:
      Name: !Sub '${AWS::StackName}-SupervisorAgentId'

  PubmedSupervisorAgentArn:
    Description: 'ARN of the PubMed Supervisor Agent'
    Value: !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/${PubmedSupervisorAgent}'
    Export:
      Name: !Sub '${AWS::StackName}-SupervisorAgentArn'

  PubmedSupervisorAgentAliasArn:
    Description: 'ARN of the PubMed Supervisor Agent Alias'
    Value: !GetAtt PubmedSupervisorAgentAlias.AgentAliasArn
    Export:
      Name: !Sub '${AWS::StackName}-SupervisorAgentAliasArn'
